// <auto-generated />
using System;
using CertBag.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CertBag.Migrations
{
    [DbContext(typeof(CertDbContext))]
    partial class CertDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("CertBag.Models.Certificate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommonName");

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<DateTime>("LastGenerationDate");

                    b.HasKey("ID");

                    b.ToTable("Certificate");
                });
#pragma warning restore 612, 618
        }
    }
}
